### ISSUE TITLE
Problem with Hummingbird 1.0.0 - the config.yml file indicates 0.2.0

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/hummingbird#675]
I was trying out the latest version of the Hummingbird theme, which should be 1.0.0. Here is the link: https://github.com/PrestaShop/hummingbird/archive/refs/tags/v1.0.0.zip

However, when I opened the config/theme.yml file, I saw `version: 0.2.0`

```yml
name: hummingbird
display_name: Hummingbird
version: 0.2.0
author:
  name: "PrestaShop Team"
  email: "pub@prestashop.com"
  url: "https://www.prestashop-project.org/"
```

Am I missing something?
